/**
 * Let tsc typecheck imports of .svelte files. The published types for the
 * Svelte entry are generated by scripts/build-svelte.mjs, not from here.
 */
declare module "*.svelte" {
  import type { Component } from "svelte";
  const component: Component<Record<string, never>>;
  export default component;
}
